const registryAbi = [
  "event DIDRegistered(string indexed did, address indexed owner, uint256 indexed robotTokenId, address robotKeyAddress, string publicKey, string metadataURI, uint256 timestamp)",
  "event DIDRevoked(string indexed did, uint256 timestamp)",
  "event DIDSuspended(string indexed did, uint256 timestamp)",
  "event DIDUnsuspended(string indexed did, uint256 timestamp)",
  "event RobotKeyRotated(string indexed did, address indexed oldKeyAddress, address indexed newKeyAddress, string oldPublicKey, string newPublicKey, uint256 timestamp)",
  "event CredentialRevoked(string indexed did, bytes32 indexed credentialHash, uint256 timestamp)",
  "event CredentialAnchored(string indexed subjectDid, bytes32 indexed credentialHash, address indexed publisher, string credentialType, uint8 consumptionMode, uint256 maxUses, uint256 timestamp)",
  "event CredentialConsumed(bytes32 indexed credentialHash, address indexed consumer, uint256 useCount, uint256 timestamp)",
  "event ControllerAdded(string indexed did, address indexed controller, uint256 permissions, uint256 timestamp)",
  "event ControllerPermissionsUpdated(string indexed did, address indexed controller, uint256 permissions, uint256 timestamp)",
  "event ControllerRemoved(string indexed did, address indexed controller, uint256 timestamp)",
  "function getDID(string did) view returns (address owner, string publicKey, string metadataURI, uint256 robotTokenId, bool active, bool suspended, uint256 suspendedAt, uint256 createdAt, uint256 updatedAt)",
  "function isActive(string did) view returns (bool)",
  "function isSuspended(string did) view returns (bool)",
  "function isRevoked(string did) view returns (bool)",
  "function getSuspendedAt(string did) view returns (uint256)",
  "function isIssuanceAllowedAt(string did, uint256 timestamp) view returns (bool)",
  "function didExists(string did) view returns (bool)",
  "function getControllers(string did) view returns (address[])",
  "function getControllerPermissions(string did, address controller) view returns (uint256)",
  "function isController(string did, address controller) view returns (bool)",
  "function addController(string did, address controller)",
  "function addController(string did, address controller, uint256 permissions)",
  "function updateControllerPermissions(string did, address controller, uint256 permissions)",
  "function removeController(string did, address controller)",
  "function robotIdentityNFT() view returns (address)",
  "function activeDIDForRobotToken(uint256 robotTokenId) view returns (string)",
  "function robotDidForToken(uint256 robotTokenId) view returns (string)",
  "function registerDID(string publicKey, address robotKeyAddress, string metadataURI, uint256 robotTokenId, bytes robotKeySignature)",
  "function updatePublicKey(string did, string newPublicKey, address newRobotKeyAddress)",
  "function suspendDID(string did)",
  "function unsuspendDID(string did)",
  "function revokeDID(string did)",
  "function revokeCredential(string did, bytes32 credentialHash)",
  "function anchorCredential(string subjectDid, bytes32 credentialHash, string credentialType, uint8 consumptionMode, uint256 maxUses)",
  "function consumeCredential(bytes32 credentialHash) returns (uint256)",
  "function isCredentialAnchored(bytes32 credentialHash) view returns (bool)",
  "function getCredentialAnchor(bytes32 credentialHash) view returns (string subjectDid, address publisher, string credentialType, uint256 publishedAt)",
  "function getConsumptionRecord(bytes32 credentialHash) view returns (uint8 mode, uint256 maxUses, uint256 useCount, bool configured)",
  "function isConsumptionAvailable(bytes32 credentialHash) view returns (bool)",
  "function CONSUMPTION_UNLIMITED() view returns (uint8)",
  "function CONSUMPTION_LIMITED() view returns (uint8)",
  "function credentialIssuerRegistry() view returns (address)",
  "function isCredentialRevoked(bytes32 credentialHash) view returns (bool)",
  "function isUsedRobotKey(address robotKeyAddress) view returns (bool)",
  "function getKeyHistoryLength(string did) view returns (uint256)",
  "function getKeyHistoryEntry(string did, uint256 index) view returns (string publicKey, address keyAddress, uint256 validFrom, uint256 validUntil)",
  "function isRobotKeyAuthorizedAt(string did, address robotKeyAddress, uint256 timestamp) view returns (bool)",
];
const robotNftAbi = [
  "event RobotMinted(uint256 indexed tokenId, address indexed owner, string metadataURI)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "function MINTER_ROLE() view returns (bytes32)",
  "function grantRole(bytes32 role, address account)",
  "function revokeRole(bytes32 role, address account)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function mintRobot(address to, string metadataURI) returns (uint256)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function safeTransferFrom(address from, address to, uint256 tokenId)",
  "function tokenURI(uint256 tokenId) view returns (string)",
];
const issuerRegistryAbi = [
  "function registerIssuer(address issuer, string metadataURI)",
  "function revokeIssuer(address issuer)",
  "function isIssuerActive(address issuer) view returns (bool)",
  "function getIssuer(address issuer) view returns (bool active, string metadataURI, uint256 updatedAt)",
  "function roleForCredentialType(string credentialType) view returns (bytes32)",
  "function isAuthorizedIssuer(string credentialType, address issuer) view returns (bool)",
  "function grantRole(bytes32 role, address account)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
];

